services:
  - type: web
    name: intro-to-transaction-processing
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Pratik:app  # <-- 'pratik' is the name of your Python file
